dist: trusty
language: minimal
services:
  - docker
script: ./run-tests.sh
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-rc\d+)?$/
env:
  global:
    secure: SsgJXgyvFn7zngIWyYKGA147R1QdHnYrsQWK1XLlJ2ISloK6kEaHZhL1ydKzJ4xRTcoPAmu1DxK4JJ3TZ7NWfCy40MUyeAwkI6IAADvuASD3gLgXYEbcgGtPVHbWjupGWUKO6fsh6bl6JIZ58sYGub9gWyThOUDJR0CwzxPZzt33pLTGv22YsAIjo+LqDFCeCCX1x81/m+rCW/xhiwBCQt5BSBN8Gw0vMHJMjAd0I0p7RYisv71Nok9Ad7ef1IYjuX8vCLZ5Xwn/SNc1bYksaSu/tifrbAJOBsRzjQG3dB7fyNuYNf1q0xYl53ZnZaMmg9IutZ0kaPgR1VkomOdyOfSNt3l6y/EO+NA+Uf8HnwTQNuTUk178cS/ywe4XoVEstuWLMgtskg+nwTdhj1togaj9wKaRMODHF9mL1WPFdVhGX7yCHXPRCAJbVoL2h6axWtXIHF7nA8uFnOef+sKodOrz8oKKdqhuDrEDL0U946H5XQel+wWxp6UjKBDrMh9+UNn1otKVdeQ1QyQtqwgqiYfnUYB8Q/o417RCBOZISgwfFZNs3ClQr0PKk2kwHowhyws+kcy3T09PyYJT8HHhrPeTtXx7qeBTNtZvp1YVcGLyVPkOhztAUaaD38zMr0F/tqaoL7bu1gB7QgDKtC7EtC6LyTTrOpuZh5UUzXLTbeA=
